### ISSUE TITLE
Hook up face tolerance

### ISSUE THREAD

**Issue by galbramc** [SCI-ElVis/ElVis#13]
Change the text to be more clear what it is.

**Comment by galbramc** [comment]
@BlakeNelson Well I thought I remembered what this was about, but now I can't. Could you post a couple more details about what the tolerance box is intended for?

**Comment by BlakeNelson** [comment]
@galbramc The face tolerance was intended to control the Newton iteration for the ray-face intersection.  I believe the tolerance is hard coded right now.

**Comment by galbramc** [comment]
@BlakeNelson Got it. Now I remember and found everything that I need to get @GPayne started on it
